/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'activityType' : ActivityType,
  'createdAt' : bigint,
  'description' : string,
  'actorId' : UserId,
  'leadId' : bigint,
}
export type ActivityType = { 'FollowUpScheduled' : null } |
  { 'FollowUpDone' : null } |
  { 'StatusChange' : null } |
  { 'NoteAdded' : null };
export interface Branch { 'name' : string, 'createdAt' : bigint }
export interface CreateLeadInput {
  'age' : bigint,
  'status' : LeadStatus,
  'branch' : string,
  'assignedTo' : [] | [UserId],
  'interest' : string,
  'source' : string,
  'score' : bigint,
  'phone' : string,
  'childName' : string,
  'parentName' : string,
}
export interface DashboardStats {
  'convertedCount' : bigint,
  'hotLeadsCount' : bigint,
  'totalLeads' : bigint,
  'pendingFollowUpsCount' : bigint,
}
export interface FollowUp {
  'createdAt' : bigint,
  'dueDate' : bigint,
  'isDone' : boolean,
  'leadId' : bigint,
  'message' : string,
}
export interface Lead {
  'age' : bigint,
  'status' : LeadStatus,
  'branch' : string,
  'assignedTo' : [] | [UserId],
  'interest' : string,
  'source' : string,
  'createdAt' : bigint,
  'score' : bigint,
  'updatedAt' : bigint,
  'phone' : string,
  'childName' : string,
  'parentName' : string,
}
export type LeadStatus = { 'New' : null } |
  { 'Contacted' : null } |
  { 'Converted' : null } |
  { 'VisitBooked' : null } |
  { 'Dropped' : null };
export interface Note {
  'content' : string,
  'authorId' : UserId,
  'createdAt' : bigint,
  'leadId' : bigint,
}
export interface UpdateLeadInput {
  'age' : [] | [bigint],
  'status' : [] | [LeadStatus],
  'branch' : [] | [string],
  'assignedTo' : [] | [[] | [UserId]],
  'interest' : [] | [string],
  'source' : [] | [string],
  'score' : [] | [bigint],
  'phone' : [] | [string],
  'childName' : [] | [string],
  'parentName' : [] | [string],
}
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNote' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBranch' : ActorMethod<[string], bigint>,
  'createFollowUp' : ActorMethod<[bigint, bigint, string], bigint>,
  'createLead' : ActorMethod<[CreateLeadInput], bigint>,
  'deleteBranch' : ActorMethod<[bigint], undefined>,
  'deleteFollowUp' : ActorMethod<[bigint], undefined>,
  'deleteLead' : ActorMethod<[bigint], undefined>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'getActivitiesByLead' : ActorMethod<[bigint], Array<Activity>>,
  'getAllBranches' : ActorMethod<[], Array<Branch>>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getFollowUpsByLead' : ActorMethod<[bigint], Array<FollowUp>>,
  'getLead' : ActorMethod<[bigint], [] | [Lead]>,
  'getLeadsByBranch' : ActorMethod<[string], Array<Lead>>,
  'getLeadsByStatus' : ActorMethod<[LeadStatus], Array<Lead>>,
  'getNotesByLead' : ActorMethod<[bigint], Array<Note>>,
  'getPendingFollowUps' : ActorMethod<[], Array<FollowUp>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markFollowUpDone' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchLeads' : ActorMethod<[string], Array<Lead>>,
  'updateLead' : ActorMethod<[bigint, UpdateLeadInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];