/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LeadStatus = IDL.Variant({
  'New' : IDL.Null,
  'Contacted' : IDL.Null,
  'Converted' : IDL.Null,
  'VisitBooked' : IDL.Null,
  'Dropped' : IDL.Null,
});
export const UserId = IDL.Principal;
export const CreateLeadInput = IDL.Record({
  'age' : IDL.Nat,
  'status' : LeadStatus,
  'branch' : IDL.Text,
  'assignedTo' : IDL.Opt(UserId),
  'interest' : IDL.Text,
  'source' : IDL.Text,
  'score' : IDL.Nat,
  'phone' : IDL.Text,
  'childName' : IDL.Text,
  'parentName' : IDL.Text,
});
export const ActivityType = IDL.Variant({
  'FollowUpScheduled' : IDL.Null,
  'FollowUpDone' : IDL.Null,
  'StatusChange' : IDL.Null,
  'NoteAdded' : IDL.Null,
});
export const Activity = IDL.Record({
  'activityType' : ActivityType,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'actorId' : UserId,
  'leadId' : IDL.Nat,
});
export const Branch = IDL.Record({ 'name' : IDL.Text, 'createdAt' : IDL.Int });
export const Lead = IDL.Record({
  'age' : IDL.Nat,
  'status' : LeadStatus,
  'branch' : IDL.Text,
  'assignedTo' : IDL.Opt(UserId),
  'interest' : IDL.Text,
  'source' : IDL.Text,
  'createdAt' : IDL.Int,
  'score' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'phone' : IDL.Text,
  'childName' : IDL.Text,
  'parentName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'convertedCount' : IDL.Nat,
  'hotLeadsCount' : IDL.Nat,
  'totalLeads' : IDL.Nat,
  'pendingFollowUpsCount' : IDL.Nat,
});
export const FollowUp = IDL.Record({
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Int,
  'isDone' : IDL.Bool,
  'leadId' : IDL.Nat,
  'message' : IDL.Text,
});
export const Note = IDL.Record({
  'content' : IDL.Text,
  'authorId' : UserId,
  'createdAt' : IDL.Int,
  'leadId' : IDL.Nat,
});
export const UpdateLeadInput = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'status' : IDL.Opt(LeadStatus),
  'branch' : IDL.Opt(IDL.Text),
  'assignedTo' : IDL.Opt(IDL.Opt(UserId)),
  'interest' : IDL.Opt(IDL.Text),
  'source' : IDL.Opt(IDL.Text),
  'score' : IDL.Opt(IDL.Nat),
  'phone' : IDL.Opt(IDL.Text),
  'childName' : IDL.Opt(IDL.Text),
  'parentName' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNote' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBranch' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createFollowUp' : IDL.Func([IDL.Nat, IDL.Int, IDL.Text], [IDL.Nat], []),
  'createLead' : IDL.Func([CreateLeadInput], [IDL.Nat], []),
  'deleteBranch' : IDL.Func([IDL.Nat], [], []),
  'deleteFollowUp' : IDL.Func([IDL.Nat], [], []),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'getActivitiesByLead' : IDL.Func([IDL.Nat], [IDL.Vec(Activity)], ['query']),
  'getAllBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getFollowUpsByLead' : IDL.Func([IDL.Nat], [IDL.Vec(FollowUp)], ['query']),
  'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
  'getLeadsByBranch' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
  'getLeadsByStatus' : IDL.Func([LeadStatus], [IDL.Vec(Lead)], ['query']),
  'getNotesByLead' : IDL.Func([IDL.Nat], [IDL.Vec(Note)], ['query']),
  'getPendingFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markFollowUpDone' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchLeads' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
  'updateLead' : IDL.Func([IDL.Nat, UpdateLeadInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LeadStatus = IDL.Variant({
    'New' : IDL.Null,
    'Contacted' : IDL.Null,
    'Converted' : IDL.Null,
    'VisitBooked' : IDL.Null,
    'Dropped' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const CreateLeadInput = IDL.Record({
    'age' : IDL.Nat,
    'status' : LeadStatus,
    'branch' : IDL.Text,
    'assignedTo' : IDL.Opt(UserId),
    'interest' : IDL.Text,
    'source' : IDL.Text,
    'score' : IDL.Nat,
    'phone' : IDL.Text,
    'childName' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const ActivityType = IDL.Variant({
    'FollowUpScheduled' : IDL.Null,
    'FollowUpDone' : IDL.Null,
    'StatusChange' : IDL.Null,
    'NoteAdded' : IDL.Null,
  });
  const Activity = IDL.Record({
    'activityType' : ActivityType,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'actorId' : UserId,
    'leadId' : IDL.Nat,
  });
  const Branch = IDL.Record({ 'name' : IDL.Text, 'createdAt' : IDL.Int });
  const Lead = IDL.Record({
    'age' : IDL.Nat,
    'status' : LeadStatus,
    'branch' : IDL.Text,
    'assignedTo' : IDL.Opt(UserId),
    'interest' : IDL.Text,
    'source' : IDL.Text,
    'createdAt' : IDL.Int,
    'score' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'phone' : IDL.Text,
    'childName' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'convertedCount' : IDL.Nat,
    'hotLeadsCount' : IDL.Nat,
    'totalLeads' : IDL.Nat,
    'pendingFollowUpsCount' : IDL.Nat,
  });
  const FollowUp = IDL.Record({
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Int,
    'isDone' : IDL.Bool,
    'leadId' : IDL.Nat,
    'message' : IDL.Text,
  });
  const Note = IDL.Record({
    'content' : IDL.Text,
    'authorId' : UserId,
    'createdAt' : IDL.Int,
    'leadId' : IDL.Nat,
  });
  const UpdateLeadInput = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'status' : IDL.Opt(LeadStatus),
    'branch' : IDL.Opt(IDL.Text),
    'assignedTo' : IDL.Opt(IDL.Opt(UserId)),
    'interest' : IDL.Opt(IDL.Text),
    'source' : IDL.Opt(IDL.Text),
    'score' : IDL.Opt(IDL.Nat),
    'phone' : IDL.Opt(IDL.Text),
    'childName' : IDL.Opt(IDL.Text),
    'parentName' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNote' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBranch' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createFollowUp' : IDL.Func([IDL.Nat, IDL.Int, IDL.Text], [IDL.Nat], []),
    'createLead' : IDL.Func([CreateLeadInput], [IDL.Nat], []),
    'deleteBranch' : IDL.Func([IDL.Nat], [], []),
    'deleteFollowUp' : IDL.Func([IDL.Nat], [], []),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'getActivitiesByLead' : IDL.Func([IDL.Nat], [IDL.Vec(Activity)], ['query']),
    'getAllBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getFollowUpsByLead' : IDL.Func([IDL.Nat], [IDL.Vec(FollowUp)], ['query']),
    'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
    'getLeadsByBranch' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
    'getLeadsByStatus' : IDL.Func([LeadStatus], [IDL.Vec(Lead)], ['query']),
    'getNotesByLead' : IDL.Func([IDL.Nat], [IDL.Vec(Note)], ['query']),
    'getPendingFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markFollowUpDone' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchLeads' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
    'updateLead' : IDL.Func([IDL.Nat, UpdateLeadInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };