/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Lead {
    age: bigint;
    status: LeadStatus;
    branch: string;
    assignedTo?: UserId;
    interest: string;
    source: string;
    createdAt: bigint;
    score: bigint;
    updatedAt: bigint;
    phone: string;
    childName: string;
    parentName: string;
}
export type UserId = Principal;
export interface Activity {
    activityType: ActivityType;
    createdAt: bigint;
    description: string;
    actorId: UserId;
    leadId: bigint;
}
export interface CreateLeadInput {
    age: bigint;
    status: LeadStatus;
    branch: string;
    assignedTo?: UserId;
    interest: string;
    source: string;
    score: bigint;
    phone: string;
    childName: string;
    parentName: string;
}
export interface UpdateLeadInput {
    age?: bigint;
    status?: LeadStatus;
    branch?: string;
    assignedTo?: UserId | null;
    interest?: string;
    source?: string;
    score?: bigint;
    phone?: string;
    childName?: string;
    parentName?: string;
}
export interface FollowUp {
    createdAt: bigint;
    dueDate: bigint;
    isDone: boolean;
    leadId: bigint;
    message: string;
}
export interface Branch {
    name: string;
    createdAt: bigint;
}
export interface DashboardStats {
    convertedCount: bigint;
    hotLeadsCount: bigint;
    totalLeads: bigint;
    pendingFollowUpsCount: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export interface Note {
    content: string;
    authorId: UserId;
    createdAt: bigint;
    leadId: bigint;
}
export enum ActivityType {
    FollowUpScheduled = "FollowUpScheduled",
    FollowUpDone = "FollowUpDone",
    StatusChange = "StatusChange",
    NoteAdded = "NoteAdded"
}
export enum LeadStatus {
    New = "New",
    Contacted = "Contacted",
    Converted = "Converted",
    VisitBooked = "VisitBooked",
    Dropped = "Dropped"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addNote(leadId: bigint, content: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBranch(name: string): Promise<bigint>;
    createFollowUp(leadId: bigint, dueDate: bigint, message: string): Promise<bigint>;
    createLead(input: CreateLeadInput): Promise<bigint>;
    deleteBranch(branchId: bigint): Promise<void>;
    deleteFollowUp(followUpId: bigint): Promise<void>;
    deleteLead(leadId: bigint): Promise<void>;
    deleteNote(noteId: bigint): Promise<void>;
    getActivitiesByLead(leadId: bigint): Promise<Array<Activity>>;
    getAllBranches(): Promise<Array<Branch>>;
    getAllLeads(): Promise<Array<Lead>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getFollowUpsByLead(leadId: bigint): Promise<Array<FollowUp>>;
    getLead(leadId: bigint): Promise<Lead | null>;
    getLeadsByBranch(branch: string): Promise<Array<Lead>>;
    getLeadsByStatus(status: LeadStatus): Promise<Array<Lead>>;
    getNotesByLead(leadId: bigint): Promise<Array<Note>>;
    getPendingFollowUps(): Promise<Array<FollowUp>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markFollowUpDone(followUpId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchLeads(searchTerm: string): Promise<Array<Lead>>;
    updateLead(leadId: bigint, input: UpdateLeadInput): Promise<void>;
}
import type { Activity as _Activity, ActivityType as _ActivityType, CreateLeadInput as _CreateLeadInput, Lead as _Lead, LeadStatus as _LeadStatus, UpdateLeadInput as _UpdateLeadInput, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addNote(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBranch(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBranch(arg0);
            return result;
        }
    }
    async createFollowUp(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createFollowUp(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFollowUp(arg0, arg1, arg2);
            return result;
        }
    }
    async createLead(arg0: CreateLeadInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(to_candid_CreateLeadInput_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(to_candid_CreateLeadInput_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteBranch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBranch(arg0);
            return result;
        }
    }
    async deleteFollowUp(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFollowUp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFollowUp(arg0);
            return result;
        }
    }
    async deleteLead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteNote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async getActivitiesByLead(arg0: bigint): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivitiesByLead(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivitiesByLead(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBranches(): Promise<Array<Branch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBranches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBranches();
            return result;
        }
    }
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getFollowUpsByLead(arg0: bigint): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowUpsByLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowUpsByLead(arg0);
            return result;
        }
    }
    async getLead(arg0: bigint): Promise<Lead | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByBranch(arg0: string): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByBranch(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByBranch(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByStatus(arg0: LeadStatus): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByStatus(to_candid_LeadStatus_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByStatus(to_candid_LeadStatus_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesByLead(arg0: bigint): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByLead(arg0);
            return result;
        }
    }
    async getPendingFollowUps(): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingFollowUps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingFollowUps();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markFollowUpDone(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markFollowUpDone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markFollowUpDone(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchLeads(arg0: string): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchLeads(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchLeads(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLead(arg0: bigint, arg1: UpdateLeadInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, to_candid_UpdateLeadInput_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, to_candid_UpdateLeadInput_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ActivityType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Activity_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_LeadStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lead]): Lead | null {
    return value.length === 0 ? null : from_candid_Lead_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    status: _LeadStatus;
    branch: string;
    assignedTo: [] | [_UserId];
    interest: string;
    source: string;
    createdAt: bigint;
    score: bigint;
    updatedAt: bigint;
    phone: string;
    childName: string;
    parentName: string;
}): {
    age: bigint;
    status: LeadStatus;
    branch: string;
    assignedTo?: UserId;
    interest: string;
    source: string;
    createdAt: bigint;
    score: bigint;
    updatedAt: bigint;
    phone: string;
    childName: string;
    parentName: string;
} {
    return {
        age: value.age,
        status: from_candid_LeadStatus_n15(_uploadFile, _downloadFile, value.status),
        branch: value.branch,
        assignedTo: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.assignedTo)),
        interest: value.interest,
        source: value.source,
        createdAt: value.createdAt,
        score: value.score,
        updatedAt: value.updatedAt,
        phone: value.phone,
        childName: value.childName,
        parentName: value.parentName
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activityType: _ActivityType;
    createdAt: bigint;
    description: string;
    actorId: _UserId;
    leadId: bigint;
}): {
    activityType: ActivityType;
    createdAt: bigint;
    description: string;
    actorId: UserId;
    leadId: bigint;
} {
    return {
        activityType: from_candid_ActivityType_n10(_uploadFile, _downloadFile, value.activityType),
        createdAt: value.createdAt,
        description: value.description,
        actorId: value.actorId,
        leadId: value.leadId
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FollowUpScheduled: null;
} | {
    FollowUpDone: null;
} | {
    StatusChange: null;
} | {
    NoteAdded: null;
}): ActivityType {
    return "FollowUpScheduled" in value ? ActivityType.FollowUpScheduled : "FollowUpDone" in value ? ActivityType.FollowUpDone : "StatusChange" in value ? ActivityType.StatusChange : "NoteAdded" in value ? ActivityType.NoteAdded : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    New: null;
} | {
    Contacted: null;
} | {
    Converted: null;
} | {
    VisitBooked: null;
} | {
    Dropped: null;
}): LeadStatus {
    return "New" in value ? LeadStatus.New : "Contacted" in value ? LeadStatus.Contacted : "Converted" in value ? LeadStatus.Converted : "VisitBooked" in value ? LeadStatus.VisitBooked : "Dropped" in value ? LeadStatus.Dropped : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CreateLeadInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateLeadInput): _CreateLeadInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_LeadStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateLeadInput_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateLeadInput): _UpdateLeadInput {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    status?: LeadStatus;
    branch?: string;
    assignedTo?: UserId | null;
    interest?: string;
    source?: string;
    score?: bigint;
    phone?: string;
    childName?: string;
    parentName?: string;
}): {
    age: [] | [bigint];
    status: [] | [_LeadStatus];
    branch: [] | [string];
    assignedTo: [] | [[] | [_UserId]];
    interest: [] | [string];
    source: [] | [string];
    score: [] | [bigint];
    phone: [] | [string];
    childName: [] | [string];
    parentName: [] | [string];
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        status: value.status ? candid_some(to_candid_LeadStatus_n5(_uploadFile, _downloadFile, value.status)) : candid_none(),
        branch: value.branch ? candid_some(value.branch) : candid_none(),
        assignedTo: value.assignedTo ? candid_some(to_candid_opt_n24(_uploadFile, _downloadFile, value.assignedTo)) : candid_none(),
        interest: value.interest ? candid_some(value.interest) : candid_none(),
        source: value.source ? candid_some(value.source) : candid_none(),
        score: value.score ? candid_some(value.score) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        childName: value.childName ? candid_some(value.childName) : candid_none(),
        parentName: value.parentName ? candid_some(value.parentName) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    status: LeadStatus;
    branch: string;
    assignedTo?: UserId;
    interest: string;
    source: string;
    score: bigint;
    phone: string;
    childName: string;
    parentName: string;
}): {
    age: bigint;
    status: _LeadStatus;
    branch: string;
    assignedTo: [] | [_UserId];
    interest: string;
    source: string;
    score: bigint;
    phone: string;
    childName: string;
    parentName: string;
} {
    return {
        age: value.age,
        status: to_candid_LeadStatus_n5(_uploadFile, _downloadFile, value.status),
        branch: value.branch,
        assignedTo: value.assignedTo ? candid_some(value.assignedTo) : candid_none(),
        interest: value.interest,
        source: value.source,
        score: value.score,
        phone: value.phone,
        childName: value.childName,
        parentName: value.parentName
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    New: null;
} | {
    Contacted: null;
} | {
    Converted: null;
} | {
    VisitBooked: null;
} | {
    Dropped: null;
} {
    return value == LeadStatus.New ? {
        New: null
    } : value == LeadStatus.Contacted ? {
        Contacted: null
    } : value == LeadStatus.Converted ? {
        Converted: null
    } : value == LeadStatus.VisitBooked ? {
        VisitBooked: null
    } : value == LeadStatus.Dropped ? {
        Dropped: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
